name: Check patch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream
          - name: centos-stream-10
            container-name: el10stream

    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
      - name: Import ovirt-master-snapshot key
        run: rpm --import https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/pubkey.gpg

      - name: Install ovirt-release-master
        run: dnf --repofrompath=ovirt-master-snapshot,https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/${{ matrix.name }}-x86_64/ install -y ovirt-release-master

      - name: Install dependencies
        run: dnf install -y --setopt=tsflags=nodocs autoconf automake dnf dnf-plugins-core dnf-plugin-versionlock gettext-devel gettext python3-devel gcc which
      
      - name: Install python dependencies
        run: dnf install -y python3-pip -y && pip install pyflakes coverage pycodestyle mock

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: automation/check-patch.sh
        # TODO: Split to separate steps?

      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts
