name: Check patch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            distro: el8stream
          - name: centos-stream-9
            distro: el9stream
    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.distro }}
    steps:
      - name: Import ovirt-master-snapshot key
        run: rpm --import https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/pubkey.gpg

      - name: Install ovirt-release-master
        run: dnf --repofrompath=ovirt-master-snapshot,https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/${{ matrix.name }}-x86_64/ install -y ovirt-release-master

      - name: Install dependencies
        run: dnf install -y --setopt=tsflags=nodocs autoconf automake dnf dnf-plugins-core dnf-plugin-versionlock gettext-devel python3-coverage python3-pycodestyle python3-pyflakes gettext python3-devel gcc which

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: automation/check-patch.sh
        # TODO: Split to separate steps?

      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@v1
        with:
          directory: exported-artifacts
          distro: ${{ matrix.distro }}
